
lic_banque:
    resource: "@LicBanqueBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation



#------------------les routes pour l'authentification--------------------

login:
    path: /login
    defaults:
        _controller: LicBanqueBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
