
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Lic\BanqueBundle\Entity\Membre: plaintext

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


  providers:
    amine:
      entity:
        class:    Lic\BanqueBundle\Entity\Membre
        property: username



  firewalls:
    amine:
      pattern:      ^/
      anonymous:    true
      provider:  amine
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login



  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }