lic_banque_homepage:
    path:     /
    defaults: { _controller: LicBanqueBundle:Compte:view }




#------------------les routes pour les mouvements--------------------

lic_banque_home:
    path:      /mouvement/{page}
    defaults:
        _controller: LicBanqueBundle:Mouvement:index
        page:        1
    requirements:
        page: \d*

lic_banque_mouvement:
    path:      /mouvement/view/{id}
    defaults:
        _controller: LicBanqueBundle:Mouvement:view
    requirements:
        id: \d+


lic_banque_ajouter:
    path:      /mouvement/ajouter
    defaults:
        _controller: LicBanqueBundle:Mouvement:ajouter

lic_banque_ajouterendur:
    path:      /mouvement/ajouterendur
    defaults:
        _controller: LicBanqueBundle:Mouvement:addendur


lic_banque_mofidier:
    path:      /mouvement/modifier/{id}
    defaults:
        _controller: LicBanqueBundle:Mouvement:modifier
    requirements:
        id: \d+


lic_banque_annuler:
    path:      /mouvement/modifier
    defaults:
        _controller: LicBanqueBundle:Mouvement:modifierendur


lic_banque_effacer:
    path:      /mouvement/sup
    defaults:
        _controller: LicBanqueBundle:Mouvement:effacerendur


#------------------les routes pour le compte--------------------

lic_banque_compte:
    path:      /compte
    defaults:
        _controller: LicBanqueBundle:Compte:view






