<?php

namespace Lic\SandboxBundle\Repository;

/**
 * CritiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
