<?php

namespace Lic\BanqueBundle\Repository;

/**
 * compteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends \Doctrine\ORM\EntityRepository
{
}
