<?php

namespace Lic\BanqueBundle\Repository;

/**
 * MouvementDebiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementDebiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
