<?php

namespace Lic\BanqueBundle\Repository;

/**
 * MouvementCrediteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementCrediteurRepository extends \Doctrine\ORM\EntityRepository
{
}
