<?php

namespace Lic\BanqueBundle\Repository;

/**
 * NiveauDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
