<?php

namespace Lic\BanqueBundle\Repository;

/**
 * PeriodiciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodiciteRepository extends \Doctrine\ORM\EntityRepository
{
}
