<?php

namespace Lic\BanqueBundle\Repository;

/**
 * RepetitifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepetitifRepository extends \Doctrine\ORM\EntityRepository
{
}
